### ISSUE TITLE
No Input in the terminal

### ISSUE THREAD

**Issue by abhijeetsingh-22** [virresh/comment_input#2]
I am using the exact code from the usage example but its not working. The execution stops at the input and I have to manually enter the input.
````c++
#include <iostream>
using namespace std;
/*input
4 "abc"
*/
int main(){
    string s;
    cin>>s;
    cout<<s<<"\n";
}
````
The execution stops here
![image](https://user-images.githubusercontent.com/55000107/89752060-5c135b00-daf0-11ea-8195-2a5cb6e862e2.png)

**Comment by virresh** [comment]
Thanks for trying out the plugin.
I see that your default shell is powershell. Can you try it once with "cmd" as the default shell?

Relevant VSCode settings:
https://code.visualstudio.com/docs/editor/integrated-terminal#_windows

**Comment by RoguedBear** [comment]
Tried it with integrated terminal and cmd. No input to program 😕 
this is happening with another similar VSCode extension which gives inputs from comment

**Comment by virresh** [comment]
@RoguedBear released an updated version on the marketplace
Can you check and confirm if the update solves your issues?

**Comment by RoguedBear** [comment]
When i ran tried to test it, it first gave "language is not supported or configured" (cant recall the exact message). But, as per your README that is due to my VSCode not installed in default location and i don't know what 'language resource folder' is.

So I'm not able to test it...

**Comment by virresh** [comment]
Oh I see
Default location is `/usr/share/code/resources/app/extensions` on linux systems
and `C:///Program Files/Microsoft VS Code/resources/app/extensions/` on windows 

I'm guessing if you install location is x, you'll find the language resources folder at `x/resources/app/extensions`

**Comment by RoguedBear** [comment]
I was not able to get it working.
My code runner runs in integrated terminal which is powershell if that helps

If there is any way i can provide logs, please let me know

**Comment by virresh** [comment]
Powershell has issues with it's integration with the sendText command, so that doesn't work. I don't know enough of Powershell internals to get it working with Powershell.

Can you try with cmd as default profile?
For logs, you can get them from https://stackoverflow.com/a/54381900/9374197

**Comment by RoguedBear** [comment]
Switching to `cmd` it did looked like something happened the first time, but that didn't seem to happen next time (seemed like a new file was created containing the partial code of the one I was running).

It didn't work afterwards, but the `SyntaxError` part of the log is recurring on each run


[ps: since the logs don't look readable (atleast to me 😅), I've also attached screenshots]

```
Some messages have been moved to the Issues panel.
VM258:1 Console was cleared
undefined
workbench.desktop.main.js:62 [Extension Host] Comment Input: Updating trigger to input
workbench.desktop.main.js:62 [Extension Host] Comment Input: Updating language config path to D:\Program Files\Microsoft VS Code\resources\app\extensions
workbench.desktop.main.js:62 [Extension Host] Comment Input: Updating delay to 500
workbench.desktop.main.js:62 [Extension Host]% {}
S @ workbench.desktop.main.js:62
$logExtensionHostMessage @ workbench.desktop.main.js:1770
_doInvokeHandler @ workbench.desktop.main.js:1770
_invokeHandler @ workbench.desktop.main.js:1770
_receiveRequest @ workbench.desktop.main.js:1770
_receiveOneMessage @ workbench.desktop.main.js:1770
(anonymous) @ workbench.desktop.main.js:1770
fire @ workbench.desktop.main.js:60
fire @ workbench.desktop.main.js:76
_receiveMessage @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
fire @ workbench.desktop.main.js:60
acceptChunk @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
_ @ workbench.desktop.main.js:2710
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
workbench.desktop.main.js:62 [Extension Host] SyntaxError: Unexpected token D in JSON at position 0    at JSON.parse (<anonymous>)    at CommentInput.<anonymous> (c:\Users\Username\.vscode\extensions\virresh.cinp-0.2.0\out\cinp.js:69:40)    at Generator.next (<anonymous>)    at c:\Users\Username\.vscode\extensions\virresh.cinp-0.2.0\out\cinp.js:8:71    at new Promise (<anonymous>)    at __awaiter (c:\Users\Username\.vscode\extensions\virresh.cinp-0.2.0\out\cinp.js:4:12)    at CommentInput.execute_code (c:\Users\Username\.vscode\extensions\virresh.cinp-0.2.0\out\cinp.js:33:16)    at c:\Users\Username\.vscode\extensions\virresh.cinp-0.2.0\out\extension.js:16:14    at E._executeContributedCommand (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:107932)    at E.$executeContributedCommand (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:108370)    at l._doInvokeHandler (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12836)    at l._invokeHandler (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12520)    at l._receiveRequest (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:11187)    at l._receiveOneMessage (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:9973)    at d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:8074    at fire (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)    at S.fire (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15497)    at d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:29764    at fire (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)    at S.fire (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15497)    at t._receiveMessage (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20755)    at d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17641    at fire (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)    at acceptChunk (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12862)    at d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12210    at Socket.v (d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:13195)    at Socket.emit (events.js:315:20)    at addChunk (internal/streams/readable.js:309:12)    at readableAddChunk (internal/streams/readable.js:284:9)    at Socket.Readable.push (internal/streams/readable.js:223:10)    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
S @ workbench.desktop.main.js:62
$logExtensionHostMessage @ workbench.desktop.main.js:1770
_doInvokeHandler @ workbench.desktop.main.js:1770
_invokeHandler @ workbench.desktop.main.js:1770
_receiveRequest @ workbench.desktop.main.js:1770
_receiveOneMessage @ workbench.desktop.main.js:1770
(anonymous) @ workbench.desktop.main.js:1770
fire @ workbench.desktop.main.js:60
fire @ workbench.desktop.main.js:76
_receiveMessage @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
fire @ workbench.desktop.main.js:60
acceptChunk @ workbench.desktop.main.js:76
(anonymous) @ workbench.desktop.main.js:76
_ @ workbench.desktop.main.js:2710
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
```


![image](https://user-images.githubusercontent.com/39442192/119270387-14dafe80-bc1a-11eb-9efb-3c7ef50f24dc.png)
![image](https://user-images.githubusercontent.com/39442192/119270451-5a97c700-bc1a-11eb-8552-371162c37d72.png)

**Comment by virresh** [comment]
Thanks for the screenshot!

It's a silly mistake on my part. Forgot to append language specific path in the user entered path due to which reading user specified language path failed

I'll fix and publish a patch tonight

**Comment by virresh** [comment]
Released v0.2.1
That should fix the issue (hopefully!)
Do try and let me know

**Comment by RoguedBear** [comment]
yes! the extension is working now!
btw, you can add a `cmd` as a requirement for integrated terminal in windows in the README.

**Comment by virresh** [comment]
Awesome

I'd added the note about cmd on windows in known issues section, probably a new requirements section is due for more visibility. Thanks for the suggestion!

Since this issue is resolved, I'll close this now.
Feel free to reopen this / open a new one if required.
